[platformio]
default_envs = esp32-cam

[env]
platform = platformio/espressif32@~6.12.0
framework = arduino
monitor_speed = 115200
lib_deps =
  bblanchon/ArduinoJson@^7.1.0

[env:esp32-cam]
board = esp32cam
build_src_filter =
  +<main_camera.cpp>

[env:esp32-api-test]
board = esp32cam
build_src_filter =
  +<main_api_test.cpp>

[env:esp32-wokwi]
board = esp32dev
build_src_filter =
  +<main_api_test.cpp>
build_flags =
  -DWOKWI_SIM=1
